#!/usr/bin/env bash

echo "Building 'ubuntu' base images"
docker image build --build-arg uid=$(id -u) --build-arg gid=$(id -g) --pull --force-rm --no-cache -t 'ubuntu' ubuntu/

echo "Building 'php' base images"
docker image build --force-rm --no-cache -t 'php' php/

echo "Building 'node' base images"
docker image build --build-arg uid=$(id -u) --build-arg gid=$(id -g) --pull --force-rm --no-cache -t 'node' node/

echo "Building 'postgresql' base images"
docker image build --pull --force-rm --no-cache -t 'postgresql' postgresql/

echo "Building 'laravel' images"
docker image build --force-rm --no-cache -t 'laravel' laravel/

echo "Building 'nextjs' images"
docker image build --force-rm --no-cache -t 'nextjs' nextjs/

echo "Building 'redis' images"
docker image build --force-rm --no-cache -t 'redis' redis/
